--? 1. Script Oracle 19c:
CREATE TABLE HEXAGONO_LOG (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CONTENIDO CLOB,
    TAMANO NUMBER,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMIT;